const detailesdata = [
  {


  },
    {
      id:1,
     img: require("../imeges/TPRODUCT/img1.jpg"),
      name: "Wireless Audio System Multiroom 360 degree Full base audio",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit",
      
    },
    {
      id:2,
        img: require("../imeges/TPRODUCT/img2.jpg"),
      name: "Tablet White EliteBook Revolve 810 G2",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {    
      id:3,
        img: require("../imeges/TPRODUCT/img3.jpg"),
      name: "Ultra Wireless S50 Headphones S50 with Bluetooth",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
      id:4,
        img: require("../imeges/TPRODUCT/img4.jpg"),
      name: "Smartphone 6S 32GB LTE",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
      id:5,
        img: require("../imeges/TPRODUCT/img5.jpg"),
      name: "Widescreen NX Mini F1 SMART NX",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
      id:6,
        img: require("../imeges/TPRODUCT/img6.jpg"),
      name: "Full Color LaserJet Pro M452dn",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
      id:7,
        img:require("../imeges/TPRODUCT/img7.jpg"),
      name: "GameConsole Destiny  Special Edition",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
      id:8,
        img: require("../imeges/TPRODUCT/img8.jpg"),
      name: "Camera C430W 4k Waterproof",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
      id:9,
        img: require("../imeges/TPRODUCT/flash-2.png"),
      name: "Watch",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
      id:10,
        img: require("../imeges/TPRODUCT/flash-4.png"),
      name: "Smart Watch Black",
      discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      
    },
    {
        id:11,
        img: require("../imeges/top/category-1.png"),
        name: "headphone",
        desc: "3k orders this week",
      },
      {
        id:12,
        img: require("../imeges/top/category-2.png"),
        name: "watch",
        desc: "4k orders this week",
      },
      {
        id:13,
        img: require("../imeges/top/category-3.png"),
        name: "sunglass",
        desc: "6k orders this week",
      },
      {
        id:14,
        img: require("../imeges/discount/discount-1.png"),
        name: "BenuX 2022",
        price: "$250",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        
        id:15,
          img: require("../imeges/discount/discount-2.png"),
        name: "Sony TV 1080p",
        price: "$450",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:16,
          img: require("../imeges/discount/discount-3.png"),
        name: "Sony PS4",
        price: "$50",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:17,
          img: require("../imeges/discount/discount-4.png"),
        name: "Setgearr 2022",
        price: "$100",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:18,
          img: require("../imeges/discount/discount-5.png"),
        name: "Tony BGB",
        price: "$20",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:19,
          img: require("../imeges/discount/discount-6.png"),
        name: "RG products",
        price: "$200",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:20,
        img: require("../imeges/discount/product-1.jpg"),
        name: "Varsi Bag ",
        price: "$48.75",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:21,
        img: require("../imeges/discount/product-2.jpg"),
        name: "Fit Twill Shirt ",
        price: "$62",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:22,
        img: require("../imeges/discount/product-4.jpg"),
        name: " Faux-Trim Shirt",
        price: "$84",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:23,
        img: require("../imeges/discount/product-5.jpg"),
        name: " Interlock Polo",
        price: "$45",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:24,
        img: require("../imeges/discount/product-8.jpg"),
        name: "Cotton Shirt",
        price: "$85",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id:25,
        img: require("../imeges/discount/product-9.jpg"),
        name: "breasted Blazer",
        price: "$32",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
      },
      {
        id: 26,
        img: require("../imeges/shops/shops-1.png"),
        name: "Mapple Earphones",
        price: "$180",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "25",
      },
      {
        id: 27,
        img: require("../imeges/shops/shops-2.png"),
        name: "Vivo android one",
        price: "$120",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "10",
      },
      {
        id: 28,
        img: require("../imeges/shops/shops-3.png"),
        name: "Sony Light",
        price: "$20",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "50 ",
      },
      {
        id: 29,
        img: require("../imeges/shops/shops-4.png"),
        name: "Iphone",
        price: "$999",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "10 ",
      },
     
      {
        id: 30,
        img: require("../imeges/shops/shops-6.png"),
        name: "Redimi Phone",
        price: "$400",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "20 ",
      },
      {
        id: 31,
        img: require("../imeges/shops/shops-7.png"),
        name: "Xeats Bluetooth",
        price: "$60",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "5 ",
      },
      {
        id: 32,
        img: require("../imeges/shops/shops-8.png"),
        name: "Airpod",
        price: "$120",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "10",
      },
      {
        id: 33,
        img: require("../imeges/shops/shops-9.png"),
        name: "Silver Cap",
        price: "$5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "2",
      },
      {
        id: 34,
        img: require("../imeges/Products/jacket-1.jpg"),
        name: "Mens Winter Leathers Jackets",
        price: "$48",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "48",
      },
      {
        id: 35,
        img: require("../imeges/Products/jacket-2.jpg"),
        name: "Mens Winter Leathers Jackets",
        price: "$32",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "25",
      },
      {
        id: 36,
        img: require("../imeges/Products/jacket-5.jpg"),
        name: "MEN Yarn Fleece Jacket",
        price: "$180",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "75",
      },
      {
        id: 37,
        img: require("../imeges/Products/jacket-6.jpg"),
        name: "MEN Yarn Fleece  Jacket",
        price: "$180",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "55",
      },
      {
        id: 38,
        img: require("../imeges/Products/shirt-1.jpg"),
        name: "Pure Garment Cotton Shirt",
        price: "$48",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "25",
      },
      {
        id: 39,
        img: require("../imeges/Products/shoe-2.jpg"),
        name: "Casual Men's Brown Shoes",
        price: "$180",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "45",
      },
      {
        id: 40,
        img: require("../imeges/Products/shoe-3.jpg"),
        name: "Men's Leather Formal ",
        price: "$180",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "65",
      },
      {
        id: 41,
        img: require("../imeges/Products/watch-1.jpg"),
        name: "Smart Watche Vital Plus",
        price: "$180",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "85",
      },
      {
        id: 42,
        img: require("../imeges/Products/shorts-1.jpg"),
        name: "French Terry Sweatshorts",
        price: "$80",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "25",
      },
      {
        id: 43,
        img: require("../imeges/Products/watch-2.jpg"),
        name: "Smart Watche",
        price: "$70",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "25",
      },
      {
        id: 44,
        img: require("../imeges/Products/sports-2.jpg"),
        name: "Trekking & Running Shoes",
        price: "$92",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "25",
      },
      {
        id: 45,
        img: require("../imeges/Products/clothes-4.jpg"),
        name: "Black Floral Wrap Midi Skirt",
        price: "$56",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab repudiandae magnam harum natus fuga",
        discount: "25",
      },
   
    
  ]
  
  export default detailesdata